use crate::intent::{GlobalConfig, Intent, Node};
use crate::paths::Paths;
use anyhow::{bail, Context, Result};
use std::fs;
use std::path::Path;

/// Build full mihomo yaml for a profile.
pub fn generate(paths: &Paths, global: &GlobalConfig, name: &str) -> Result<String> {
    let intent = Intent::load(&paths.profile_intent(name))?;
    let mixed_port = intent.mixed_port.unwrap_or(global.mixed_port);

    let mut manual_names: Vec<String> = intent.nodes.iter().map(|n| n.name.clone()).collect();
    let has_sub = intent.subscription.is_some();

    // proxies section (manual only; sub via provider)
    let proxies: Vec<serde_yaml::Value> = intent.nodes.iter().map(Node::to_yaml_value).collect();

    // proxy-providers
    let mut providers = serde_yaml::Mapping::new();
    if has_sub {
        let cache = paths.sub_cache(name);
        if !cache.exists() {
            bail!(
                "subscription cache missing for '{name}'; run: mm sub update {name}"
            );
        }
        // use file provider pointing at our cache (absolute path)
        let mut p = serde_yaml::Mapping::new();
        p.insert("type".into(), "file".into());
        p.insert(
            "path".into(),
            cache.to_string_lossy().to_string().into(),
        );
        p.insert("interval".into(), 3600.into());
        p.insert(
            "exclude-filter".into(),
            r"过期时间|剩余流量|sub\.info|官网|套餐".into(),
        );
        let mut hc = serde_yaml::Mapping::new();
        hc.insert("enable".into(), true.into());
        hc.insert("interval".into(), 600.into());
        hc.insert("url".into(), "https://www.gstatic.com/generate_204".into());
        p.insert("health-check".into(), serde_yaml::Value::Mapping(hc));
        providers.insert(format!("{name}-sub").into(), serde_yaml::Value::Mapping(p));
    }

    // proxy-groups: single PROXY select
    let mut group = serde_yaml::Mapping::new();
    group.insert("name".into(), "PROXY".into());
    group.insert("type".into(), "select".into());
    let mut group_proxies: Vec<serde_yaml::Value> =
        manual_names.drain(..).map(|n| n.into()).collect();
    group_proxies.push("DIRECT".into());
    group.insert("proxies".into(), group_proxies.into());
    if has_sub {
        group.insert(
            "use".into(),
            serde_yaml::Value::Sequence(vec![format!("{name}-sub").into()]),
        );
    }

    // rules: custom file or default
    let rules_path = paths.profile_rules(name);
    let (rule_providers, rules) = if rules_path.exists() {
        load_custom_rules(&rules_path)?
    } else {
        default_rules(paths)?
    };

    let mut root = serde_yaml::Mapping::new();
    root.insert("allow-lan".into(), true.into());
    root.insert("mode".into(), "rule".into());
    root.insert("log-level".into(), "warning".into());
    // true: TUN can install IPv6 routes (stops OS IPv6 leaking via wlan)
    root.insert("ipv6".into(), true.into());
    root.insert(
        "external-controller".into(),
        global.controller.clone().into(),
    );
    root.insert("secret".into(), global.secret.clone().into());
    root.insert("unified-delay".into(), true.into());
    root.insert("mixed-port".into(), mixed_port.into());

    // tun
    let mut tun = serde_yaml::Mapping::new();
    tun.insert("enable".into(), intent.tun.into());
    tun.insert("stack".into(), "gvisor".into());
    tun.insert("auto-route".into(), true.into());
    // tighter routing → fewer bypass leaks (LAN still matches DIRECT rules)
    tun.insert("strict-route".into(), true.into());
    tun.insert("auto-detect-interface".into(), true.into());
    tun.insert(
        "dns-hijack".into(),
        serde_yaml::Value::Sequence(vec!["any:53".into()]),
    );
    root.insert("tun".into(), serde_yaml::Value::Mapping(tun));

    root.insert("dns".into(), default_dns());
    root.insert("sniffer".into(), default_sniffer());

    let mut profile = serde_yaml::Mapping::new();
    profile.insert("store-selected".into(), true.into());
    root.insert("profile".into(), serde_yaml::Value::Mapping(profile));

    if !proxies.is_empty() {
        root.insert("proxies".into(), proxies.into());
    }
    if !providers.is_empty() {
        root.insert(
            "proxy-providers".into(),
            serde_yaml::Value::Mapping(providers),
        );
    }
    root.insert(
        "proxy-groups".into(),
        serde_yaml::Value::Sequence(vec![serde_yaml::Value::Mapping(group)]),
    );
    if let Some(rp) = rule_providers {
        root.insert("rule-providers".into(), rp);
    }
    root.insert("rules".into(), rules);

    let yaml = serde_yaml::to_string(&serde_yaml::Value::Mapping(root))?;
    // header comment
    Ok(format!(
        "# generated by mm — do not edit; source: profiles/{name}.toml\n{yaml}"
    ))
}

pub fn write_runtime(paths: &Paths, global: &GlobalConfig, name: &str) -> Result<std::path::PathBuf> {
    let yaml = generate(paths, global, name)?;
    let out = paths.runtime_yaml(name);
    fs::write(&out, yaml)?;
    // keep current in sync if this is active
    if paths.active_file().exists() {
        if let Ok(active) = paths.read_active() {
            if active == name {
                fs::copy(&out, paths.current_yaml())?;
            }
        }
    }
    Ok(out)
}

fn load_custom_rules(
    path: &Path,
) -> Result<(Option<serde_yaml::Value>, serde_yaml::Value)> {
    let s = fs::read_to_string(path)?;
    let v: serde_yaml::Value = serde_yaml::from_str(&s).context("parse custom rules yaml")?;
    match v {
        serde_yaml::Value::Mapping(m) => {
            let rp = m.get(&serde_yaml::Value::String("rule-providers".into())).cloned();
            let rules = m
                .get(&serde_yaml::Value::String("rules".into()))
                .cloned()
                .context("custom rules yaml must contain `rules:`")?;
            Ok((rp, rules))
        }
        serde_yaml::Value::Sequence(_) => Ok((None, v)),
        _ => bail!("custom rules yaml must be a mapping with rules: or a rules list"),
    }
}

fn default_dns() -> serde_yaml::Value {
    let yaml = r#"
enable: true
ipv6: false
enhanced-mode: fake-ip
fake-ip-range: 198.18.0.1/16
fake-ip-filter-mode: blacklist
fake-ip-filter:
  - "*.lan"
  - "*.local"
  - "*.arpa"
  - "time.*.com"
  - "ntp.*.org"
  - "+.market.xiaomi.com"
  - "localhost.ptlogin2.qq.com"
  - "*.msftncsi.com"
  - "www.msftconnecttest.com"
default-nameserver:
  - system
  - 223.6.6.6
  - 8.8.8.8
nameserver:
  - 8.8.8.8
  - https://doh.pub/dns-query
  - https://dns.alidns.com/dns-query
proxy-server-nameserver:
  - https://doh.pub/dns-query
  - https://dns.alidns.com/dns-query
  - tls://223.5.5.5
use-hosts: true
use-system-hosts: true
"#;
    serde_yaml::from_str(yaml).expect("dns template")
}

/// Recover domain from TLS/HTTP for fake-ip + pure-IP destinations.
fn default_sniffer() -> serde_yaml::Value {
    let yaml = r#"
enable: true
force-dns-mapping: true
parse-pure-ip: true
override-destination: true
sniff:
  HTTP:
    ports: [80, 8080-8880]
    override-destination: true
  TLS:
    ports: [443, 8443]
  QUIC:
    ports: [443, 8443]
"#;
    serde_yaml::from_str(yaml).expect("sniffer template")
}

fn default_rules(paths: &Paths) -> Result<(Option<serde_yaml::Value>, serde_yaml::Value)> {
    // DustinWin ruleset — same set as user's work yaml
    let base = "https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset";
    let ruleset_dir = paths.run_dir().join("ruleset");
    fs::create_dir_all(&ruleset_dir)?;

    let entries: &[(&str, &str, &str, &str)] = &[
        ("private", "domain", "mrs", "private.mrs"),
        ("applications", "classical", "text", "applications.list"),
        ("bilibili", "domain", "mrs", "bilibili.mrs"),
        ("apple-cn", "domain", "mrs", "apple-cn.mrs"),
        ("microsoft-cn", "domain", "mrs", "microsoft-cn.mrs"),
        ("games-cn", "domain", "mrs", "games-cn.mrs"),
        ("cn", "domain", "mrs", "cn.mrs"),
        ("privateip", "ipcidr", "mrs", "privateip.mrs"),
        ("cnip", "ipcidr", "mrs", "cnip.mrs"),
    ];

    let mut rp = serde_yaml::Mapping::new();
    for (name, behavior, format, file) in entries {
        let mut m = serde_yaml::Mapping::new();
        m.insert("type".into(), "http".into());
        m.insert("behavior".into(), (*behavior).into());
        m.insert("format".into(), (*format).into());
        m.insert(
            "path".into(),
            ruleset_dir.join(file).to_string_lossy().to_string().into(),
        );
        m.insert("url".into(), format!("{base}/{file}").into());
        m.insert("interval".into(), 86400.into());
        m.insert("proxy".into(), "PROXY".into());
        rp.insert((*name).into(), serde_yaml::Value::Mapping(m));
    }

    let rules: Vec<serde_yaml::Value> = vec![
        "RULE-SET,private,DIRECT".into(),
        "RULE-SET,applications,DIRECT".into(),
        "RULE-SET,bilibili,DIRECT".into(),
        "RULE-SET,apple-cn,DIRECT".into(),
        "RULE-SET,microsoft-cn,DIRECT".into(),
        "RULE-SET,games-cn,DIRECT".into(),
        "RULE-SET,cn,DIRECT".into(),
        "RULE-SET,privateip,DIRECT,no-resolve".into(),
        "RULE-SET,cnip,DIRECT".into(),
        "MATCH,PROXY".into(),
    ];

    Ok((
        Some(serde_yaml::Value::Mapping(rp)),
        serde_yaml::Value::Sequence(rules),
    ))
}
